language: php

dist: trusty
sudo: false

php:
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv rehash

install:
  - composer install --prefer-source

script:
  - bin/phpspec run --no-interaction -vvv -f progress

cache:
  directories:
    - $HOME/.composer/cache
